version: "3.9"
services:
  queue:
    image: rabbitmq:3.9.9-management
    ports:
    - 5672:5672
    - 15672:15672
  results:
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
    ports:
      - 19200:9200